### ISSUE TITLE
Submit of contribution *meme hunter*

### ISSUE THREAD

**Issue by SukiCZ** [aeternity/hackathon-prague#12]
Hi and thanks for having our team on site.
I would like to submit our meme hunter app and I'm not sure where to submit it. Will try to do it here.

Here is the [repo](http://github.com/SukiCZ/meme_hunter)
Link to our [presentation](https://docs.google.com/presentation/d/1fOHKyA2l9Tpnxhp8Uas2xItZaPRIWQz4AeJIX5dhZ80/edit?usp=sharing)

Our team:

@Jkat (smart contract)
@SukiCZ (python dev)
[Ethan Clime](https://www.facebook.com/ethan.clime) (Mental support, presentation and everything else)

Cheers :clinking_glasses:

**Comment by thepiwo** [comment]
added it here: https://github.com/aeternity/hackathon-prague/blob/master/README.md
