### ISSUE TITLE
[Mentor request] 

### ISSUE THREAD

**Issue by emmanuelJet** [aeternity/hackathon-prague#3]
# Mentor help/advice request

## How do we find you?
```
Contact
---
Name: Emmanuel Joseph (JET)
Devchat nickname: @emmanuelJet
Location: 
    [*] Online
    [ ] Onsite (desk number [ ])
```

## Issue

I want to add State Channel functionalities to my state contract and I don't know how to go about it

**Comment by thepiwo** [comment]
Hello @emmanuelJet,

thanks for your question.
State channels are on the level above the smart contract, so you will have to open a state channel using the core node, then you will be able to deploy and use smart contracts within this state channel.

There is state channels support in the JS-SDK currently and you can find the protocol definition of state channels here: https://github.com/aeternity/protocol/tree/master/channels
