### ISSUE TITLE
[Mentor request]

### ISSUE THREAD

**Issue by jabz1** [aeternity/hackathon-prague#4]
# online Participation 

## How do we find you?
```
Contact
---
Name: Jabz
Devchat nickname: @jabz
Location: 
    [ ] Uganda
    [ ] Kampala
```

## Issue

Online participants forexample we from Uganda had issues with connectivity, we were left behind on the hack day.
Can we still participate on the available teams and most especially those who were interested in participating as UX designers and Entreprenuers?

**Comment by ErkanKanden** [comment]
@jabz1 Yes, you can join the existing teams. Please write me in private which team you would like to join.
