### ISSUE TITLE
[Technical support] 

### ISSUE THREAD

**Issue by heclinares** [aeternity/hackathon-prague#5]
# Technical problem report / Request for support
Calling Node API /debug/contracts/call gets me the error:
{"reason":"Not byte array: call_data"}
Need some help finding the right way to encode call_data field...

## How do we find you?
```
Contact
---
Name: Héctor
Devchat nickname: @vector4d
Location: 
    [ ] Online
    [ x] Onsite (desk number [ ])
```

## Issue

Deployed a testing smart contract
Using curl to contact test-net node, using this command:
curl -d '{"caller_id": "ak_kJmcyuEBfAxcUYqQXyba2NVhj24uRx4SVsuXrUECTkorhEuzv", "nonce": 1,   "contract_id": "ct_cWvk6pJdwVXFvEJ41YxgdzpSJdNNrbYs7c3GoNfz3k9mejnkR", "abi_version": 1, "fee": 0, "ttl": 0, "amount": 0, "gas": 10, "gas_price": 100,  "call_data": "contract HelloHackaton = entrypoint hello_Hackaton() : string function __call() = HelloHackaton()"}' -H "Content-Type: application/json" https://sdk-testnet.aepps.com/v2/debug/contracts/call

Get the error message:
{"reason":"Not byte array: call_data"}

Seems like I'm missing something in the call_data content, some help would be appreciated.

### Expected behaviour

Explain what is the expected behaviour.

### Steps to reproduce problem

What are the steps to reproduce this problem.

### Environment

If its a technical issue provide information regarding the environment you are using when facing the problem.

- OS:
- Network:
- Compiler version:
- Tools:

**Comment by nikita-fuchs** [comment]
Hey, it's highly recommended to use an SDK for this, what language are you working with ?

**Comment by heclinares** [comment]
Ok, we were exploring the option to connect from a woocommerce server to a smart contract, to generate some products based on the info stored in the contract.
Np, will do something with js then

**Comment by mradkov** [comment]
If you use [waellet](https://github.com/waellet/waellet) you can interact with your contract easily: see how [waellet's wiki](https://github.com/waellet/waellet/wiki/Aepp)
