### ISSUE TITLE
[Technical support] 

### ISSUE THREAD

**Issue by Kromha** [aeternity/hackathon-prague#6]
# Technical problem report / Request for support

## How do we find you?
```
Contact
---
Name: Hector Toledo
Devchat nickname: @
Location: 
    [x ] Online
    [ ] Onsite (desk number [ ])
```

## Issue

Error when I try to code fungible token

### Expected behaviour

Code should check if address is correct

require(account != #0, "Invalid address")

### Steps to reproduce problem

stateful entrypoint mint(account: address, value: int) : bool =
    only_owner()
    require(account != #0, "Invalid address")

    put(state{total_supply = add(state.total_supply, value),
      balances[account] = add(balance_of(account), value)})

    true

### Environment

FireEditor

**Comment by Kromha** [comment]
Compiler:
type_error: Cannot unify bytes(1) and address
At: Line 72, column 21

**Comment by thepiwo** [comment]
this thread may help you: https://forum.aeternity.com/t/zero-address-literal/4704

**Comment by nikita-fuchs** [comment]
hey @Kromha , I suppose you want to check whether the `account` is not undefined in the function call ? No need for that, sophia does this automatically for you: If you give your function a parameter, it _is_ required automatically. except if you would make the parameter type an `option(address)` , then you would need to check with a `switch` statement whether the address has a value or not.

So, in your case, this require is not needed. Hint: `#`  indicates the datatype bytes, therefore the error ;)

**Comment by Kromha** [comment]
Okey, thank you!
